<?php

namespace MediaWiki\Extension\SemanticSchemas\Tests\Unit\Schema;

use InvalidArgumentException;
use MediaWiki\Extension\SemanticSchemas\Schema\SubobjectModel;
use PHPUnit\Framework\TestCase;

/**
 * @covers \MediaWiki\Extension\SemanticSchemas\Schema\SubobjectModel
 */
class SubobjectModelTest extends TestCase {

	/* =========================================================================
	 * CONSTRUCTOR VALIDATION
	 * ========================================================================= */

	public function testEmptyNameThrowsException(): void {
		$this->expectException( InvalidArgumentException::class );
		$this->expectExceptionMessage( 'empty' );
		new SubobjectModel( '' );
	}

	public function testWhitespaceOnlyNameThrowsException(): void {
		$this->expectException( InvalidArgumentException::class );
		new SubobjectModel( '   ' );
	}

	public function testInvalidCharactersInNameThrowsException(): void {
		$this->expectException( InvalidArgumentException::class );
		$this->expectExceptionMessage( 'invalid characters' );
		new SubobjectModel( 'Subobject<with>invalid' );
	}

	public function testDuplicateRequiredOptionalPropertyPromotesToRequired(): void {
		$model = new SubobjectModel( 'TestSubobject', [
			'properties' => [
				'required' => [ 'Has name' ],
				'optional' => [ 'Has name', 'Has email' ],
			],
		] );

		$this->assertContains( 'Has name', $model->getRequiredProperties() );
		$this->assertNotContains( 'Has name', $model->getOptionalProperties() );
		$this->assertContains( 'Has email', $model->getOptionalProperties() );
	}

	public function testNoConflictPropertiesUnchanged(): void {
		$model = new SubobjectModel( 'TestSubobject', [
			'properties' => [
				'required' => [ 'Has name' ],
				'optional' => [ 'Has email' ],
			],
		] );

		$this->assertEquals( [ 'Has name' ], $model->getRequiredProperties() );
		$this->assertEquals( [ 'Has email' ], $model->getOptionalProperties() );
	}

	public function testNonArrayPropertiesThrowsException(): void {
		$this->expectException( InvalidArgumentException::class );
		new SubobjectModel( 'TestSubobject', [
			'properties' => 'not an array',
		] );
	}

	/* =========================================================================
	 * BASIC ACCESSORS
	 * ========================================================================= */

	public function testGetNameReturnsCorrectValue(): void {
		$model = new SubobjectModel( 'TestSubobject' );
		$this->assertEquals( 'TestSubobject', $model->getName() );
	}

	public function testGetNameTrimmed(): void {
		$model = new SubobjectModel( '  TestSubobject  ' );
		$this->assertEquals( 'TestSubobject', $model->getName() );
	}

	public function testGetLabelReturnsLabelWhenSet(): void {
		$model = new SubobjectModel( 'TestSubobject', [ 'label' => 'Test Label' ] );
		$this->assertEquals( 'Test Label', $model->getLabel() );
	}

	public function testGetLabelAutoGeneratedWhenEmpty(): void {
		$model = new SubobjectModel( 'Has_test_subobject', [ 'label' => '' ] );
		$this->assertEquals( 'Test Subobject', $model->getLabel() );
	}

	public function testGetLabelDefaultsToNameWhenNotSet(): void {
		$model = new SubobjectModel( 'TestSubobject' );
		$this->assertEquals( 'TestSubobject', $model->getLabel() );
	}

	public function testGetDescriptionReturnsCorrectValue(): void {
		$model = new SubobjectModel( 'TestSubobject', [ 'description' => 'Test description' ] );
		$this->assertEquals( 'Test description', $model->getDescription() );
	}

	public function testGetDescriptionReturnsEmptyWhenNotSet(): void {
		$model = new SubobjectModel( 'TestSubobject' );
		$this->assertSame( '', $model->getDescription() );
	}

	/* =========================================================================
	 * PROPERTY ACCESSORS
	 * ========================================================================= */

	public function testGetRequiredProperties(): void {
		$model = new SubobjectModel( 'TestSubobject', [
			'properties' => [
				'required' => [ 'Has name', 'Has email' ],
				'optional' => [],
			],
		] );
		$this->assertEquals( [ 'Has name', 'Has email' ], $model->getRequiredProperties() );
	}

	public function testGetOptionalProperties(): void {
		$model = new SubobjectModel( 'TestSubobject', [
			'properties' => [
				'required' => [],
				'optional' => [ 'Has phone', 'Has address' ],
			],
		] );
		$this->assertEquals( [ 'Has phone', 'Has address' ], $model->getOptionalProperties() );
	}

	public function testGetAllPropertiesCombinesBoth(): void {
		$model = new SubobjectModel( 'TestSubobject', [
			'properties' => [
				'required' => [ 'Has name' ],
				'optional' => [ 'Has email' ],
			],
		] );
		$allProps = $model->getAllProperties();
		$this->assertContains( 'Has name', $allProps );
		$this->assertContains( 'Has email', $allProps );
		$this->assertCount( 2, $allProps );
	}

	public function testIsPropertyRequiredReturnsTrue(): void {
		$model = new SubobjectModel( 'TestSubobject', [
			'properties' => [
				'required' => [ 'Has name' ],
				'optional' => [ 'Has email' ],
			],
		] );
		$this->assertTrue( $model->isPropertyRequired( 'Has name' ) );
	}

	public function testIsPropertyRequiredReturnsFalse(): void {
		$model = new SubobjectModel( 'TestSubobject', [
			'properties' => [
				'required' => [ 'Has name' ],
				'optional' => [ 'Has email' ],
			],
		] );
		$this->assertFalse( $model->isPropertyRequired( 'Has email' ) );
	}

	/* =========================================================================
	 * EXPORT
	 * ========================================================================= */

	public function testToArrayContainsAllFields(): void {
		$model = new SubobjectModel( 'TestSubobject', [
			'label' => 'Test Label',
			'description' => 'Test description',
			'properties' => [
				'required' => [ 'Has name' ],
				'optional' => [ 'Has email' ],
			],
		] );

		$array = $model->toArray();
		$this->assertArrayHasKey( 'label', $array );
		$this->assertArrayHasKey( 'description', $array );
		$this->assertArrayHasKey( 'properties', $array );
		$this->assertArrayHasKey( 'required', $array['properties'] );
		$this->assertArrayHasKey( 'optional', $array['properties'] );
	}
}
