<?php

namespace MediaWiki\Extension\SemanticSchemas\Generator;

use MediaWiki\Extension\SemanticSchemas\Schema\CategoryModel;
use MediaWiki\Extension\SemanticSchemas\Schema\EffectiveCategoryModel;
use MediaWiki\Extension\SemanticSchemas\Schema\FieldModel;
use MediaWiki\Extension\SemanticSchemas\Schema\InheritanceResolver;
use MediaWiki\Extension\SemanticSchemas\Schema\PropertyModel;
use MediaWiki\Extension\SemanticSchemas\Store\PageCreator;
use MediaWiki\Extension\SemanticSchemas\Store\WikiCategoryStore;
use MediaWiki\Extension\SemanticSchemas\Store\WikiPropertyStore;
use MediaWiki\Extension\SemanticSchemas\Util\NamingHelper;

/**
 * FormGenerator
 * --------------
 * Generates PageForms markup for category creation/editing forms.
 *
 * Features:
 * - Automatic field generation from CategoryModel schema
 * - Required and optional property sections
 * - Subobject repeatable blocks with minimum instances
 * - Namespace support for page creation
 * - Automatic hierarchy preview (when parent category property detected)
 */
class FormGenerator {

	private PageCreator $pageCreator;
	private WikiPropertyStore $propertyStore;
	private PropertyInputMapper $inputMapper;
	private WikiCategoryStore $categoryStore;

	public function __construct(
		PageCreator $pageCreator,
		WikiPropertyStore $propertyStore,
		PropertyInputMapper $inputMapper,
		WikiCategoryStore $categoryStore
	) {
		$this->pageCreator = $pageCreator;
		$this->propertyStore = $propertyStore;
		$this->inputMapper = $inputMapper;
		$this->categoryStore = $categoryStore;
	}

	private function s( ?string $v ): string {
		return $v ?? '';
	}

	/**
	 * Generate the PageForms wrapper form for a category.
	 *
	 * This is a thin wrapper that transcludes the composite form
	 * (Form:Category/composite) which contains the actual field definitions.
	 * The wrapper adds the standalone form chrome: forminput header,
	 * namespace targeting, hierarchy preview, free text, and buttons.
	 *
	 * @param EffectiveCategoryModel $category The effective (merged) category
	 * @return string
	 */
	public function generateForm( EffectiveCategoryModel $category ): string {
		$name = trim( $category->getName() );

		$lines = [];

		/* <noinclude> Header */
		$lines[] = '<noinclude>';
		$lines[] = '<!-- AUTO-GENERATED by SemanticSchemas - DO NOT EDIT MANUALLY -->';
		$lines[] = '<!-- This form is automatically regenerated -->';
		$lines[] = 'This is the form for editing [[:Category:' . $this->s( $name ) . ']] pages.';

		$formInput = [
			'form=' . $this->s( $name ),
			'autocomplete on category=' . $this->s( $name ),
		];

		if ( $category->getTargetNamespace() !== null ) {
			$formInput[] = 'namespace=' . $this->s( $category->getTargetNamespace() );
		}

		$lines[] = '{{#forminput:' . implode( '|', $formInput ) . '}}';

		$lines[] = '</noinclude><includeonly>';
		$lines[] = '';

		/* Page name info (for namespace targeting) */
		if ( $category->getTargetNamespace() !== null ) {
			// PageForms requires {{{info|page name=Namespace:<page name>}}} to create
			// pages in a specific namespace. The <page name> placeholder is filled by
			// PageForms with the user-entered page name.
			$lines[] = '{{{info|page name=' . $this->s( $category->getTargetNamespace() ) . ':<page name>}}}';
			$lines[] = '';
		}

		/* Field definitions via composite form transclusion.
		 * MW strips the <nowiki> tags during transclusion, so PageForms
		 * sees the raw {{{...}}} directives. */
		$lines[] = '{{Form:' . $this->s( $name ) . '/composite}}';
		$lines[] = '';

		/* Hierarchy Preview (if parent category property exists) */
		$parentProp = $this->findParentCategoryProperty( $category );
		if ( $parentProp !== null ) {
			$lines[] = '{{#semanticschemas_load_form_preview:}}';
			$lines[] = '';

			$parentParam = NamingHelper::propertyToParameter( $parentProp );

			$lines[] = '<!-- Auto-populated category membership field -->';
			$lines[] = '{{{standard input|free text|hidden|rows=1'
				. '|placeholder=Parent categories will be added automatically|id=s2-parent-categories}}}';
			$lines[] = '';

			$lines[] = "'''Hierarchy Preview:'''";
			$lines[] = '<div id="s2-form-hierarchy-preview" data-parent-field="'
				. $this->s( $parentParam ) . '"></div>';
			$lines[] = '';
		}

		/* Free text section */
		$lines[] = "'''Free text:'''";
		$lines[] = '';
		$lines[] = '{{{standard input|free text|rows=10}}}';
		$lines[] = '';

		/* Summary + Buttons */
		$lines[] = '{{{standard input|summary}}}';
		$lines[] = '';
		$lines[] = '{{{standard input|save}}} '
			. '{{{standard input|preview}}} '
			. '{{{standard input|changes}}} '
			. '{{{standard input|cancel}}}';
		$lines[] = '</includeonly>';

		return implode( "\n", $lines );
	}

	/**
	 * Generate property fields in a table format.
	 * Separates required and optional properties into distinct sections.
	 */
	private function generatePropertyTable( CategoryModel $category ): array {
		$fields = $category->getPropertyFields();
		$required = array_values( array_filter(
			$fields,
			static fn ( FieldModel $f ) => $f->isRequired()
		) );
		$optional = array_values( array_filter(
			$fields,
			static fn ( FieldModel $f ) => !$f->isRequired()
		) );

		$out = [];
		$out = array_merge( $out, $this->generatePropertySection( $required, 'Required fields' ) );
		$out = array_merge( $out, $this->generatePropertySection( $optional, 'Optional fields' ) );

		return $out;
	}

	/**
	 * Generate a property section with label and table.
	 *
	 * @param FieldModel[] $fields
	 * @param string $label Section label
	 * @return array Lines of wikitext
	 */
	private function generatePropertySection(
		array $fields,
		string $label
	): array {
		if ( $fields === [] ) {
			return [];
		}

		$out = [];
		$out[] = "'''" . $label . ":'''";
		$out[] = '';
		$out[] = '{| class="formtable"';

		foreach ( $fields as $field ) {
			$out = array_merge( $out, $this->generateTableField( $field ) );
		}

		$out[] = '|}';
		$out[] = '';

		return $out;
	}

	/**
	 * Generate a table row for a property field with label and description.
	 *
	 * @param FieldModel $field
	 * @return array Lines of wikitext
	 */
	private function generateTableField( FieldModel $field ): array {
		$propertyName = $field->getName();
		$isRequired = $field->isRequired();

		$prop = $this->propertyStore->readProperty( $propertyName )
			?: new PropertyModel( $propertyName, [ 'datatype' => 'Page' ] );

		if ( $prop->isHidden() ) {
			return [];
		}

		$param = $field->getParameterName();
		$label = $this->s( $prop->getLabel() );
		$description = $this->s( $prop->getDescription() );

		// Special handling for "Has Type" property
		if ( strcasecmp( $propertyName, 'Has type' ) === 0 ) {
			$input = $this->generateHasTypeInput( $isRequired );
		} else {
			$input = $this->inputMapper->generateInputDefinition( $prop, $isRequired );
		}

		$out = [];
		$out[] = '|-';

		$labelLine = '! ' . $label;
		if ( $isRequired ) {
			$labelLine .= '<span style="color:red;"> *</span>';
		}
		$labelLine .= ':';
		if ( $description !== '' ) {
			$labelLine .= ' <br><p class="pfFieldDescription" style="font-size:0.7em; color:gray;">'
				. htmlspecialchars( $description, ENT_QUOTES )
				. '</p>';
		}
		$out[] = $labelLine;

		$out[] = '| {{{field|' . $param . '|property=' . $this->s( $prop->getName() ) . '|' . $input . '}}}';

		return $out;
	}

	/**
	 * Generate input definition for "Has Type" property with SMW datatypes.
	 */
	private function generateHasTypeInput( bool $isRequired ): string {
		$datatypes = PropertyModel::getValidDatatypes();

		$params = [
			'input type=dropdown',
			'values=' . implode( ',', $datatypes )
		];

		if ( $isRequired ) {
			$params[] = 'mandatory=true';
		}

		return implode( '|', $params );
	}

	/**
	 * Subobject sections: transclude each subobject category's composite form
	 * in subobject mode instead of duplicating its field definitions.
	 */
	private function generateSubobjectSections(
		CategoryModel $category,
		InheritanceResolver $resolver
	): array {
		$subFields = $category->getSubobjectFields();
		if ( $subFields === [] ) {
			return [];
		}

		$out = [];

		foreach ( $subFields as $field ) {
			$subName = $field->getName();

			if ( !$resolver->hasCategory( $subName ) ) {
				continue;
			}

			$params = [ 'subobject=true' ];
			if ( $field->isRequired() ) {
				$params[] = 'required=true';
			}

			$out[] = '{{Form:' . $this->s( $subName )
				. '/composite|' . implode( '|', $params ) . '}}';
			$out[] = '';
		}

		return $out;
	}

	/* ----------------------------------------------------------
	 * Save + utilities
	 * -------------------------------------------------------- */

	public function updateForm( string $name, string $content ): bool {
		if ( trim( $name ) === '' ) {
			throw new \InvalidArgumentException( "Form name cannot be empty" );
		}

		$title = $this->pageCreator->makeTitle( $name, \PF_NS_FORM );
		if ( !$title ) {
			wfLogWarning( "SemanticSchemas: Unable to create form title for '$name'" );
			return false;
		}

		$result = $this->pageCreator->createOrUpdatePage(
			$title,
			$content,
			'SemanticSchemas: Auto-generated form'
		);

		// Purge the form page cache to ensure PageForms sees the updated content.
		// This is critical when form parameters like namespace targeting change,
		// as PageForms caches the parsed form definition.
		if ( $result ) {
			$this->pageCreator->purgePage( $title );
		}

		return $result;
	}

	public function generateAndSaveForm( EffectiveCategoryModel $category ): bool {
		try {
			$txt = $this->generateForm( $category );
			return $this->updateForm( $category->getName(), $txt );
		} catch ( \Exception $e ) {
			wfLogWarning(
				"SemanticSchemas: Failed to gen/save form for {$category->getName()}: "
				. $e->getMessage()
			);
			return false;
		}
	}

	/**
	 * Generate a composite form slot for a category.
	 *
	 * Produces a form fragment with nowiki-wrapped field directives,
	 * designed to be transcluded via {{Form:Category/composite}}.
	 *
	 * Supports two modes via template parameters:
	 *   - Standalone (default): {{{for template|Category}}} with <h2> heading
	 *   - Subobject ({{{subobject|}}}): {{{for template|Category/subobject|multiple}}}
	 *     with <h3> heading; {{{required|}}} adds |minimum instances=1
	 *
	 * This means a parent form's subobject section can simply transclude
	 * {{Form:SubobjectCategory/composite|subobject=true|required=true}}
	 * instead of duplicating the subobject's field definitions.
	 */
	public function generateCompositeForm(
		EffectiveCategoryModel $category,
		InheritanceResolver $resolver
	): string {
		$name = trim( $category->getName() );
		$label = trim( $category->getLabel() );
		$escapedLabel = htmlspecialchars( $label, ENT_QUOTES );

		$lines = [];

		$lines[] = '<noinclude>';
		$lines[] = '<!-- AUTO-GENERATED by SemanticSchemas - DO NOT EDIT MANUALLY -->';
		$lines[] = '<!-- Composite form slot for ' . $name . ' -->';
		$lines[] = '</noinclude><includeonly>';

		// Heading: <h3> in subobject mode, <h2> in standalone mode
		$lines[] = '{{#if:{{{subobject|}}}|<h3>' . $escapedLabel
			. '</h3>|<h2>' . $escapedLabel . '</h2>}}';
		$lines[] = '';

		// For-template directive: subobject mode switches to /subobject|multiple,
		// with optional minimum instances for required subobjects.
		// {{{subobject|}}} and {{{required|}}} are resolved during transclusion;
		// the <nowiki> tags protect the PageForms {{{...}}} directives from
		// being parsed as template parameters.
		$subFor = $this->s( $name ) . '/subobject|multiple';
		$lines[] = '{{#if:{{{subobject|}}}';
		$lines[] = '|{{#if:{{{required|}}}';
		$lines[] = '|<nowiki>{{{for template|' . $subFor . '|minimum instances=1}}}</nowiki>';
		$lines[] = '|<nowiki>{{{for template|' . $subFor . '}}}</nowiki>';
		$lines[] = '}}';
		$lines[] = '|<nowiki>{{{for template|' . $this->s( $name ) . '}}}</nowiki>';
		$lines[] = '}}';
		$lines[] = '';

		$fieldLines = $this->generatePropertyTable( $category );
		$lines = array_merge( $lines, $this->wrapNowiki( $fieldLines ) );

		$lines[] = '<nowiki>{{{end template}}}</nowiki>';
		$lines[] = '';

		$subLines = $this->generateSubobjectSections( $category, $resolver );
		$lines = array_merge( $lines, $this->wrapNowiki( $subLines ) );

		$lines[] = '</includeonly>';

		return implode( "\n", $lines );
	}

	public function generateAndSaveCompositeForm(
		EffectiveCategoryModel $category,
		InheritanceResolver $resolver
	): bool {
		try {
			$txt = $this->generateCompositeForm( $category, $resolver );
			return $this->updateForm( $category->getName() . '/composite', $txt );
		} catch ( \Exception $e ) {
			wfLogWarning(
				"SemanticSchemas: Failed to gen/save composite form for {$category->getName()}: "
				. $e->getMessage()
			);
			return false;
		}
	}

	/**
	 * Generate and save both the regular form and composite form.
	 */
	public function generateAndSaveAllForms(
		EffectiveCategoryModel $category,
		InheritanceResolver $resolver
	): bool {
		$formSuccess = $this->generateAndSaveForm( $category );
		$compositeSuccess = $this->generateAndSaveCompositeForm( $category, $resolver );
		return $formSuccess && $compositeSuccess;
	}

	public function formExists( string $categoryName ): bool {
		$t = $this->pageCreator->makeTitle( $categoryName, \PF_NS_FORM );
		return $t && $this->pageCreator->pageExists( $t );
	}

	/**
	 * Wrap all {{{...}}} occurrences in <nowiki> tags and convert wiki
	 * headings to HTML headings (wiki headings don't survive transclusion).
	 */
	private function wrapNowiki( array $lines ): array {
		return array_map( static function ( $line ) {
			$line = preg_replace( '/^===\s*(.+?)\s*===$/', '<h3>$1</h3>', $line );
			$line = preg_replace( '/^==\s*(.+?)\s*==$/', '<h2>$1</h2>', $line );

			return preg_replace( '/(\{\{\{[^}]*\}\}\})/', '<nowiki>$1</nowiki>', $line );
		}, $lines );
	}

	/**
	 * Find the parent category property in a category's schema.
	 */
	private function findParentCategoryProperty( CategoryModel $category ): ?string {
		foreach ( $category->getPropertyFields() as $field ) {
			$lc = strtolower( $field->getName() );

			if (
				str_contains( $lc, 'parent' ) &&
				str_contains( $lc, 'category' )
			) {
				return $field->getName();
			}
		}

		return null;
	}
}
