<?php

namespace MediaWiki\Extension\StructureSync\Generator;

use MediaWiki\Extension\StructureSync\Schema\CategoryModel;
use MediaWiki\Extension\StructureSync\Store\PageCreator;
use MediaWiki\Extension\StructureSync\Schema\PropertyModel;

/**
 * TemplateGenerator
 * -----------------
 * Generates:
 *   - Semantic templates   → Template:<Category>/semantic
 *   - Dispatcher templates → Template:<Category>
 *
 * Semantic templates store SMW data using #set.
 * Dispatcher templates wrap semantic + display templates.
 */
class TemplateGenerator
{

    /** @var PageCreator */
    private $pageCreator;

    /**
     * @param PageCreator|null $pageCreator
     */
    public function __construct(PageCreator $pageCreator = null)
    {
        $this->pageCreator = $pageCreator ?? new PageCreator();
    }

    /**
     * Sanitize a value to ensure MediaWiki never encounters null.
     *
     * @param string|null $value
     * @return string
     */
    private function sanitize(?string $value): string
    {
        return $value ?? '';
    }

    /* =====================================================================
     * SEMANTIC TEMPLATE
     * ===================================================================== */

    /**
     * Generate semantic template wikitext for a category.
     *
     * Output location:
     *   Template:<Category>/semantic
     *
     * @param CategoryModel $category Effective (inherited) category
     * @return string
     */
    public function generateSemanticTemplate(CategoryModel $category): string
    {

        $properties = $category->getAllProperties();
        sort($properties); // Deterministic output

        $lines = [];

        /* ------------------------------------------------------------------
         * NOINCLUDE HEADER
         * ------------------------------------------------------------------ */
        $lines[] = '<noinclude>';
        $lines[] = '<!-- AUTO-GENERATED by StructureSync - DO NOT EDIT MANUALLY -->';
        $lines[] = '<!-- This semantic template stores SMW data for the category. -->';
        $lines[] = 'Semantic data template for [[Category:' . $this->sanitize($category->getName()) . ']].';
        $lines[] = '</noinclude><includeonly>';

        /* ------------------------------------------------------------------
         * SMW DATA (#set)
         * ------------------------------------------------------------------ */
        $lines[] = '{{#set:';

        foreach ($properties as $property) {
            $param = $this->sanitize($this->propertyToParameter($property));
            $propertySafe = $this->sanitize($property);
            $lines[] = ' | ' . $propertySafe . ' = {{{' . $param . '|}}}';
        }

        $lines[] = '}}';

        /* ------------------------------------------------------------------
         * Category annotation
         * ------------------------------------------------------------------ */
        $lines[] = '';
        $lines[] = '[[Category:' . $this->sanitize($category->getName()) . ']]';

        $lines[] = '</includeonly>';

        return implode("\n", $lines);
    }

    /* =====================================================================
     * DISPATCHER TEMPLATE
     * ===================================================================== */

    /**
     * Generate dispatcher template wikitext for the category.
     *
     * Output location:
     *   Template:<Category>
     *
     * Dispatcher template ensures:
     *   - semantic template applied
     *   - display template applied
     *
     * @param CategoryModel $category Effective (inherited) category
     * @return string
     */
    public function generateDispatcherTemplate(CategoryModel $category): string
    {

        $properties = $category->getAllProperties();
        sort($properties);

        $name = $this->sanitize($category->getName());

        $lines = [];

        /* ------------------------------------------------------------------
         * NOINCLUDE
         * ------------------------------------------------------------------ */
        $lines[] = '<noinclude>';
        $lines[] = '<!-- AUTO-GENERATED by StructureSync - DO NOT EDIT MANUALLY -->';
        $lines[] = '<!-- This dispatcher template loads semantic + display templates. -->';
        $lines[] = 'Dispatcher for [[Category:' . $name . ']].';
        $lines[] = '* Semantic: [[Template:' . $name . '/semantic]]';
        $lines[] = '* Display:  [[Template:' . $name . '/display]]';
        $lines[] = '</noinclude><includeonly>';

        /* ------------------------------------------------------------------
         * DEFAULT FORM (for "edit with form" button)
         * ------------------------------------------------------------------ */
        $lines[] = '{{#default_form:' . $name . '}}';
        $lines[] = '';

        /* ------------------------------------------------------------------
         * SEMANTIC TEMPLATE INCLUDE
         * ------------------------------------------------------------------ */
        $lines[] = '{{' . $name . '/semantic';
        foreach ($properties as $property) {
            $param = $this->sanitize($this->propertyToParameter($property));
            $propertySafe = $this->sanitize($property);
            $lines[] = ' | ' . $propertySafe . ' = {{{' . $param . '|}}}';
        }
        $lines[] = '}}';
        $lines[] = '';

        /* ------------------------------------------------------------------
         * DISPLAY TEMPLATE INCLUDE
         * ------------------------------------------------------------------ */

        $lines[] = '{{' . $name . '/display';
        foreach ($properties as $property) {
            $param = $this->sanitize($this->propertyToParameter($property));
            $lines[] = ' | ' . $param . ' = {{{' . $param . '|}}}';
        }
        $lines[] = '}}';

        $lines[] = '</includeonly>';

        return implode("\n", $lines);
    }


    /* =====================================================================
     * TEMPLATE CREATION / UPDATING
     * ===================================================================== */

    /**
     * Create or update a template page.
     *
     * @param string $templateName  Name without namespace prefix
     * @param string $content
     * @return bool
     */
    public function updateTemplate(string $templateName, string $content): bool
    {

        $title = $this->pageCreator->makeTitle($templateName, NS_TEMPLATE);
        if (!$title) {
            return false;
        }

        $summary = 'StructureSync: Auto-generated template';
        return $this->pageCreator->createOrUpdatePage($title, $content, $summary);
    }

    /**
     * Generate semantic + dispatcher templates for a category.
     *
     * @param CategoryModel $category
     * @return array{success:bool,errors:string[]}
     */
    public function generateAllTemplates(CategoryModel $category): array
    {

        $result = ['success' => true, 'errors' => []];
        $name = $category->getName();

        /* ------------------------------------------------------------------
         * SEMANTIC TEMPLATE
         * ------------------------------------------------------------------ */
        $semantic = $this->generateSemanticTemplate($category);
        if (!$this->updateTemplate($name . '/semantic', $semantic)) {
            $result['success'] = false;
            $result['errors'][] = "Failed to create semantic template for $name";
        }

        /* ------------------------------------------------------------------
         * DISPATCHER TEMPLATE
         * ------------------------------------------------------------------ */
        $dispatcher = $this->generateDispatcherTemplate($category);
        if (!$this->updateTemplate($name, $dispatcher)) {
            $result['success'] = false;
            $result['errors'][] = "Failed to create dispatcher template for $name";
        }

        return $result;
    }

    /* =====================================================================
     * UTILITIES
     * ===================================================================== */

    /**
     * Convert SMW property names → PageForms parameter names.
     *   "Has full name" → "full_name"
     *   "Foaf:name"     → "foaf_name"
     *
     * @param string $propertyName
     * @return string
     */
    private function propertyToParameter(string $propertyName): string
    {

        // Remove "Has " prefix
        $param = $propertyName;
        if (str_starts_with($param, 'Has ')) {
            $param = substr($param, 4);
        }

        // Replace ":" with "_" (safe for PageForms)
        $param = str_replace(':', '_', $param);

        // Normalize spacing
        $param = strtolower(trim($param));
        $param = str_replace(' ', '_', $param);

        return $param;
    }

    /**
     * Check if semantic template exists.
     *
     * @param string $categoryName
     * @return bool
     */
    public function semanticTemplateExists(string $categoryName): bool
    {
        $title = $this->pageCreator->makeTitle($categoryName . '/semantic', NS_TEMPLATE);
        return $title && $this->pageCreator->pageExists($title);
    }

    /**
     * Check if dispatcher template exists.
     *
     * @param string $categoryName
     * @return bool
     */
    public function dispatcherTemplateExists(string $categoryName): bool
    {
        $title = $this->pageCreator->makeTitle($categoryName, NS_TEMPLATE);
        return $title && $this->pageCreator->pageExists($title);
    }
}
