<?php

namespace MediaWiki\Extension\SemanticSchemas\Generator;

use InvalidArgumentException;
use MediaWiki\Extension\SemanticSchemas\Schema\CategoryModel;
use MediaWiki\Extension\SemanticSchemas\Schema\EffectiveCategoryModel;
use MediaWiki\Extension\SemanticSchemas\Schema\InheritanceResolver;
use MediaWiki\Extension\SemanticSchemas\Schema\PropertyModel;
use MediaWiki\Extension\SemanticSchemas\Store\PageCreator;
use MediaWiki\Extension\SemanticSchemas\Store\WikiPropertyStore;
use MediaWiki\Extension\SemanticSchemas\Util\Constants;
use MediaWiki\Extension\SemanticSchemas\Util\NamingHelper;
use MediaWiki\Language\Language;

/**
 * Generates core templates for proper Semantic MediaWiki functioning.
 *
 * Responsibilities:
 *   - Semantic template: Template:<Category>/semantic (stores data via #set)
 *   - Dispatcher template: Template:<Category> (coordinates form, storage, and display)
 *   - Subobject templates: Template:<Name>/subobject (for nested data via #subobject)
 */
class TemplateGenerator {

	private PageCreator $pageCreator;
	private WikiPropertyStore $propertyStore;
	private Language $language;

	public function __construct(
		PageCreator $pageCreator,
		WikiPropertyStore $propertyStore,
		Language $language
	) {
		$this->pageCreator = $pageCreator;
		$this->propertyStore = $propertyStore;
		$this->language = $language;
	}

	/* =====================================================================
	 * PROPERTY VALUE EXPRESSION HELPER
	 * ===================================================================== */

	/**
	 * Generate the property line for a semantic template's #set block.
	 *
	 * For Page-type properties with allowedNamespace, this adds the namespace
	 * prefix to ensure SMW correctly interprets values as page references.
	 *
	 * This is necessary because Page Forms autocomplete returns bare page names
	 * without namespace prefixes (e.g. "MyPage" instead of "Project:MyPage").
	 * The template must re-add the prefix so SMW stores the fully qualified
	 * page reference.
	 *
	 * @param string $propertyName The SMW property name
	 * @param string $param The template parameter name
	 * @return string The wikitext for the property line
	 */
	private function generatePropertyLine( string $propertyName, string $param ): string {
		$propModel = $this->propertyStore->readProperty( $propertyName );

		// Default: simple property = value
		if ( !$propModel instanceof PropertyModel ) {
			return ' | ' . $propertyName . ' = {{{' . $param . '|}}}';
		}

		$allowedNamespace = $propModel->getAllowedNamespace();

		// Non-Page or no namespace restriction: simple assignment
		if ( !$propModel->isPageType() || $allowedNamespace === null || $allowedNamespace === '' ) {
			if ( $propModel->allowsMultipleValues() ) {
				return ' | ' . $propertyName . ' = {{{' . $param . '|}}} |+sep=,';
			}
			return ' | ' . $propertyName . ' = {{{' . $param . '|}}}';
		}

		if ( $propModel->allowsMultipleValues() ) {
			// Multi-value Page property with namespace: prefix each value via #arraymap inside #set
			return ' | ' . $propertyName . ' = {{#arraymap:{{{' . $param .
				'|}}}|,|@@item@@|' . $allowedNamespace . ':@@item@@|,}} |+sep=,';
		}

		// Single value: conditional prefix
		return ' | ' . $propertyName . ' = {{#if:{{{' . $param . '|}}}|' .
			$allowedNamespace . ':{{{' . $param . '|}}}|}}';
	}

	/* =====================================================================
	 * SEMANTIC TEMPLATE  (Template:<Category>/semantic)
	 * ===================================================================== */

	/**
	 * Generate content for the semantic template.
	 *
	 * Each semantic template calls its direct parents' semantic templates
	 * (forwarding effective props) and stores its own properties via #set.
	 *
	 * @param CategoryModel $category The raw (own-properties-only) category
	 * @param array<string,EffectiveCategoryModel> $parentEffectives Parent name → effective model
	 * @return string
	 */
	public function generateSemanticTemplate(
		CategoryModel $category,
		array $parentEffectives = []
	): string {
		$name = trim( $category->getName() );
		if ( $name === '' ) {
			throw new InvalidArgumentException( "Category name cannot be empty" );
		}

		$props = $category->getAllProperties();
		sort( $props );

		$out = [];
		$out[] = '<noinclude>';
		$out[] = '<!-- AUTO-GENERATED by SemanticSchemas - DO NOT EDIT MANUALLY -->';
		$out[] = 'Semantic template for Category:' . $name;
		$out[] = '</noinclude><includeonly>';

		/* Embed parent semantic templates */
		foreach ( $parentEffectives as $parentName => $parentEffective ) {
			$parentProps = $parentEffective->getAllProperties();
			sort( $parentProps );
			$out = array_merge(
				$out,
				$this->generateTemplateCall( $parentName . '/semantic', $parentProps )
			);
			$out[] = '';
		}

		/* Own property storage */
		$out[] = '{{#set:';

		foreach ( $props as $p ) {
			$param = NamingHelper::propertyToParameter( $p );
			$out[] = $this->generatePropertyLine( $p, $param );
		}

		$out[] = '}}';

		$out[] = '</includeonly>';

		return implode( "\n", $out );
	}

	/* =====================================================================
	 * DISPATCHER TEMPLATE (Template:<Category>)
	 * ===================================================================== */

	/**
	 * Generate a template call with property parameter passthrough.
	 *
	 * @param string $templateName Template name to call
	 * @param array $props List of property names
	 * @return array Lines of wikitext
	 */
	private function generateTemplateCall( string $templateName, array $props ): array {
		$out = [];
		$out[] = '{{' . $templateName;
		foreach ( $props as $p ) {
			$param = NamingHelper::propertyToParameter( $p );
			$out[] = ' | ' . $param . ' = {{{' . $param . '|}}}';
		}
		$out[] = '}}';
		return $out;
	}

	/**
	 * Generate content for the dispatcher template.
	 *
	 * @param EffectiveCategoryModel $effective The fully merged category
	 * @return string
	 */
	public function generateDispatcherTemplate(
		EffectiveCategoryModel $effective
	): string {
		$name = trim( $effective->getName() );
		if ( $name === '' ) {
			throw new InvalidArgumentException( "Category name cannot be empty" );
		}

		$allProps = $effective->getAllProperties();
		sort( $allProps );

		$out = [];
		$out[] = '<noinclude>';
		$out[] = '<!-- AUTO-GENERATED by SemanticSchemas - DO NOT EDIT MANUALLY -->';
		$out[] = 'Dispatcher template for Category:' . $name;
		$out[] = '</noinclude><includeonly>';
		$out[] = '{{#default_form:' . $name . '}}';
		$out[] = '';

		/* Semantic storage */
		$out = array_merge( $out, $this->generateTemplateCall( $name . '/semantic', $allProps ) );
		$out[] = '';

		/* Display template */
		$out = array_merge( $out, $this->generateTemplateCall( $name . '/display', $allProps ) );
		$out[] = '';

		/* Category membership */
		// FIXME: Temporary special-case hack to exclude Category:Category membership -
		// prevent categories from inheriting the metacategory fields.
		// To be resolved in #122 after removing the need for generation,
		// where this will become part of the pre-packaged Template:Category template
		$categoryPrefix = $this->language->getFormattedNsText( NS_CATEGORY );
		if ( $name !== $categoryPrefix ) {
			$out[] = '[[' . $categoryPrefix . ':' . $name . ']]';
		}
		$out[] = '[[Category:' . Constants::SEMANTICSCHEMAS_MANAGED_CATEGORY . ']]';

		$out[] = '</includeonly>';

		return implode( "\n", $out );
	}

	/* =====================================================================
	 * SUBOBJECT TEMPLATES  (Template:<Name>/subobject)
	 *
	 * Subobject types are categories. The generator reads the category schema
	 * via WikiCategoryStore and produces templates that use SMW's @category
	 * mechanism for typing instead of a custom Has subobject type property.
	 * ===================================================================== */

	private function generateSubobjectTemplate( EffectiveCategoryModel $sub ): string {
		$name = $sub->getName();

		$out = [];
		$out[] = '<noinclude>';
		$out[] = '<!-- AUTO-GENERATED by SemanticSchemas - DO NOT EDIT MANUALLY -->';
		$out[] = 'Subobject template for Category:' . $name;
		$out[] = '</noinclude><includeonly>';

		$out[] = '{{#subobject:';
		$out[] = ' |@category=' . $name;

		$props = $sub->getAllProperties();

		foreach ( $props as $p ) {
			$param = NamingHelper::propertyToParameter( $p );
			$out[] = $this->generatePropertyLine( $p, $param );
		}

		$out[] = '}}';
		$out[] = '</includeonly>';

		return implode( "\n", $out );
	}

	/* =====================================================================
	 * PUBLIC: FULL TEMPLATE GENERATION ENTRYPOINT
	 * ===================================================================== */

	/**
	 * Generate all artifacts for a category (semantic, dispatcher, subobjects).
	 *
	 * @param CategoryModel $category The raw (own-properties-only) category
	 * @param InheritanceResolver $resolver
	 * @return array{success: bool, errors: string[]}
	 */
	public function generateAllTemplates(
		CategoryModel $category,
		InheritanceResolver $resolver
	): array {
		$errors = [];
		$name = $category->getName();
		$effective = $resolver->getEffectiveCategory( $name );

		/* Semantic template — own declared properties only */
		try {
			$parentEffectives = $resolver->getParentEffectiveModels( $name );
			$content = $this->generateSemanticTemplate( $category, $parentEffectives );
			$this->updateTemplate( $name . '/semantic', $content );
		} catch ( \Exception $e ) {
			$errors[] = "Error generating semantic template for $name: " . $e->getMessage();
		}

		/* Dispatcher */
		try {
			$content = $this->generateDispatcherTemplate( $effective );
			$this->updateTemplate( $name, $content );
		} catch ( \Exception $e ) {
			$errors[] = "Error generating dispatcher template for $name: " . $e->getMessage();
		}

		/* Subobject template — every category gets one */
		try {
			$content = $this->generateSubobjectTemplate( $effective );
			$this->updateTemplate( $name . '/subobject', $content );
		} catch ( \Exception $e ) {
			$errors[] = "Error generating subobject template for $name: " . $e->getMessage();
		}

		return [
			'success' => !$errors,
			'errors' => $errors
		];
	}

	/* =====================================================================
	 * BASIC UPDATE WRAPPER
	 * ===================================================================== */

	private function updateTemplate( string $name, string $content ): bool {
		if ( trim( $name ) === '' ) {
			throw new InvalidArgumentException( "Template name cannot be empty" );
		}

		$title = $this->pageCreator->makeTitle( $name, NS_TEMPLATE );
		if ( !$title ) {
			wfLogWarning( "SemanticSchemas: Failed to create Title for template '$name'" );
			return false;
		}

		return $this->pageCreator->createOrUpdatePage(
			$title,
			$content,
			'SemanticSchemas: Auto-generated template'
		);
	}

	/**
	 * Check if the semantic template exists for a category.
	 *
	 * @param string $categoryName
	 * @return bool
	 */
	public function semanticTemplateExists( string $categoryName ): bool {
		$templateName = trim( $categoryName ) . '/semantic';
		$title = $this->pageCreator->makeTitle( $templateName, NS_TEMPLATE );
		return $title && $this->pageCreator->pageExists( $title );
	}
}
